name: Deployment
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{secrets.HOST}}
          USERNAME: ${{secrets.USER_NAME}}
          PORT: ${{secrets.PORT}}
          KEY: ${{secrets.WEBINME_SECRET}}
        with:
          rm: true
          source: "."
          target: "/var/www/test/public"

      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          USERNAME: ${{secrets.USER_NAME}}
          PORT: ${{secrets.PORT}}
          KEY: ${{secrets.WEBINME_SECRET}}
          script: |
            cd /var/www/test/public
            npm i
            cd client
            npm i
            npm run build
            mv build ../
            rm -rf *
            cd ..
            mv build ./client
            rm -rf .git*