name: Deployment
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          host: webinme.ru
          username: xxx44552
          port: 22
          key: ${{secrets.WEBINME_SECRET}}
        with:
          source: "."
          target: "/home/xxx44552/app"

      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: webinme.ru
          username: xxx44552
          port: 22
          key: ${{secrets.WEBINME_SECRET}}
          script: |
            cd /home/${{secrets.USER_NAME}}/app
            npm i
            cd client
            npm i
            npm run build
            mv build ../
            rm -rf *
            cd ../
            rm -rf client
