name: Deployment
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: webinme.ru
          USERNAME: xxx44552
          PORT: 22
          KEY: ${{secrets.WEBINME_SECRET}}
        with:
          source: "."
          target: "/home/${{secrets.USER_NAME}}/app"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: webinme.ru
          USERNAME: xxx44552
          PORT: 22
          KEY: ${{secrets.WEBINME_SECRET}}
          script: |
            cd /home/xxx44552/app
            npm i
            cd client
            npm i
            npm run build
            mv build ../
            rm -rf src