#name: Deployment
#on:
#  push:
#    branches: [ master ]
#
#jobs:
#  job_one:
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: test
#        uses: appleboy/ssh-action@master
#        with:
#          host: webinme.ru
#          username: xxx44552
#          key: ${{secrets.WEBINME_SECRET}}
#          port: 22
#          script: |
#            cd portfolio_template
#            echo "yes" > test.txt

name: Deploy to production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    steps:
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: xxx44552
          HOST: webinme.ru
          KEY: ${{secrets.WEBINME_SECRET}}
        with:
          source: './*'
          target: './awd/'