name: Deployment
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: test
      uses: appleboy/ssh-action@master
      with:
        host: webinme.ru
        username: xxx44552
        key: ${{secrets.WEBINME_SECRET}}
        posr: 22
        script: |
          pwd
          git pull origin master
          git status