name: Deployment
on:
  push:
    branches: [ master ]

#jobs:
#  job_one:
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: test
#        uses: appleboy/ssh-action@master
#        with:
#          host: webinme.ru
#          username: xxx44552
#          key: ${{secrets.WEBINME_SECRET}}
#          port: 22
#          script: |
#            cd portfolio_template
#            echo "yes" > test.txt

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: webinme.ru
          USERNAME: xxx44552
          PORT: 22
          KEY: ${{secrets.WEBINME_SECRET}}
        with:
          source: "."
          target: "/home/xxx44552/app"

      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: webinme.ru
          USERNAME: xxx44552
          PORT: 22
          KEY: ${{secrets.WEBINME_SECRET}}
          script: cat /home/xxx44552/app/README.md