name: Deployment
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: webinme.ru
          USERNAME: xxx44552
          PORT: 22
          KEY: ${{secrets.WEBINME_SECRET}}
          script: |
            echo "${{secrets.WEBINME_SECRET}} --- ${{secrets.PORT}} --- ${{secrets.USER_NAME}} --- ${{secrets.HOST}}" > test.txt
            